/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bb5896c96a86406ea940ae91673723ee)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DRAWTHIS_OPENVERSE_ENABLED: "false";
	DRAWTHIS_LOCAL_REFERENCES_ENABLED: "false";
	DRAWTHIS_PEXELS_ENABLED: string;
	DRAWTHIS_PEXELS_API_KEY: string;
	DRAWTHIS_PEXELS_API_BASE_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
