import type { ReferenceSearchSeed } from './feed-policy';

const peopleSeeds = [
	{
		id: 'people-gesture-walking-stride',
		label: 'Walking stride gesture',
		query: 'person walking full body gesture reference photo',
		primarySubject: 'people',
		topic: 'gesture-action',
		sceneTypes: ['everyday-life'],
		focuses: ['gesture', 'proportion', 'negative-space'],
		complexity: 'simple',
		coverageTags: ['gesture', 'mundane']
	},
	{
		id: 'people-gesture-reaching-bending',
		label: 'Reaching and bending pose',
		query: 'person reaching bending pose reference photo',
		primarySubject: 'people',
		topic: 'gesture-action',
		focuses: ['gesture', 'construction', 'anatomy'],
		complexity: 'moderate',
		coverageTags: ['gesture', 'body-parts']
	},
	{
		id: 'people-gesture-dance-action',
		label: 'Dance action gesture',
		query: 'dancer action pose gesture reference photo',
		primarySubject: 'people',
		topic: 'gesture-action',
		focuses: ['gesture', 'shape', 'composition'],
		complexity: 'moderate',
		coverageTags: ['gesture']
	},
	{
		id: 'people-gesture-sports-motion',
		label: 'Sports motion pose',
		query: 'athlete motion pose full body reference photo',
		primarySubject: 'people',
		topic: 'gesture-action',
		focuses: ['gesture', 'proportion', 'anatomy'],
		complexity: 'complex',
		coverageTags: ['gesture', 'body-parts']
	},
	{
		id: 'people-full-standing-casual',
		label: 'Casual standing figure',
		query: 'casual standing person full body reference photo',
		primarySubject: 'people',
		topic: 'full-figure',
		sceneTypes: ['everyday-life'],
		focuses: ['proportion', 'construction', 'anatomy'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['mundane', 'body-parts']
	},
	{
		id: 'people-full-seated-chair',
		label: 'Seated figure in chair',
		query: 'person sitting in chair full body reference photo',
		primarySubject: 'people',
		topic: 'full-figure',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['proportion', 'construction', 'negative-space'],
		complexity: 'moderate',
		coverageTags: ['mundane', 'negative-space']
	},
	{
		id: 'people-full-crouching-squatting',
		label: 'Crouching figure',
		query: 'person crouching squatting full body pose reference photo',
		primarySubject: 'people',
		topic: 'full-figure',
		focuses: ['gesture', 'proportion', 'anatomy'],
		complexity: 'moderate',
		coverageTags: ['gesture', 'body-parts']
	},
	{
		id: 'people-full-everyday-task',
		label: 'Figure doing everyday task',
		query: 'person doing everyday task full body reference photo',
		primarySubject: 'people',
		topic: 'full-figure',
		secondarySubjects: ['objects'],
		sceneTypes: ['everyday-life', 'interior'],
		focuses: ['gesture', 'composition', 'proportion'],
		complexity: 'complex',
		coverageTags: ['mundane', 'gesture']
	},
	{
		id: 'people-portrait-front-face',
		label: 'Front portrait',
		query: 'front face portrait reference photo natural light',
		primarySubject: 'people',
		topic: 'portrait-head',
		sceneTypes: ['close-up'],
		focuses: ['proportion', 'anatomy', 'value'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['portrait']
	},
	{
		id: 'people-portrait-profile-head',
		label: 'Profile head',
		query: 'side profile portrait head reference photo',
		primarySubject: 'people',
		topic: 'portrait-head',
		sceneTypes: ['close-up'],
		focuses: ['shape', 'proportion', 'anatomy'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['portrait']
	},
	{
		id: 'people-portrait-three-quarter',
		label: 'Three-quarter portrait',
		query: 'three quarter view portrait head reference photo',
		primarySubject: 'people',
		topic: 'portrait-head',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'proportion', 'light-shadow'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['portrait', 'construction-practice']
	},
	{
		id: 'people-portrait-older-face',
		label: 'Older face portrait',
		query: 'older person portrait face reference photo',
		primarySubject: 'people',
		topic: 'portrait-head',
		sceneTypes: ['close-up'],
		focuses: ['value', 'texture', 'anatomy'],
		complexity: 'complex',
		orientation: 'portrait',
		coverageTags: ['portrait', 'texture-study']
	},
	{
		id: 'people-expression-smile-laugh',
		label: 'Smiling or laughing face',
		query: 'smiling laughing face expression reference photo',
		primarySubject: 'people',
		topic: 'expression',
		sceneTypes: ['close-up'],
		focuses: ['anatomy', 'shape', 'proportion'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['expression', 'portrait']
	},
	{
		id: 'people-expression-surprised',
		label: 'Surprised expression',
		query: 'surprised face expression portrait reference photo',
		primarySubject: 'people',
		topic: 'expression',
		sceneTypes: ['close-up'],
		focuses: ['shape', 'anatomy', 'gesture'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['expression', 'portrait']
	},
	{
		id: 'people-expression-tired-thinking',
		label: 'Tired or thinking expression',
		query: 'tired thinking face expression reference photo',
		primarySubject: 'people',
		topic: 'expression',
		sceneTypes: ['close-up', 'everyday-life'],
		focuses: ['value', 'composition', 'anatomy'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['expression', 'mundane']
	},
	{
		id: 'people-hands-open-palm',
		label: 'Open hand and palm',
		query: 'open hand palm close up reference photo',
		primarySubject: 'people',
		topic: 'hands-feet',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'anatomy', 'shape'],
		complexity: 'moderate',
		coverageTags: ['hands', 'body-parts', 'construction-practice']
	},
	{
		id: 'people-hands-gripping-object',
		label: 'Hand gripping object',
		query: 'hand gripping object close up reference photo',
		primarySubject: 'people',
		topic: 'hands-feet',
		secondarySubjects: ['objects'],
		sceneTypes: ['close-up', 'everyday-life'],
		focuses: ['construction', 'anatomy', 'negative-space'],
		complexity: 'complex',
		coverageTags: ['hands', 'body-parts', 'negative-space']
	},
	{
		id: 'people-hands-holding-cup',
		label: 'Hands holding cup',
		query: 'hands holding mug cup reference photo',
		primarySubject: 'people',
		topic: 'hands-feet',
		secondarySubjects: ['objects'],
		sceneTypes: ['close-up', 'everyday-life'],
		focuses: ['shape', 'construction', 'material'],
		complexity: 'moderate',
		coverageTags: ['hands', 'mundane']
	},
	{
		id: 'people-feet-bare-standing',
		label: 'Bare feet standing',
		query: 'bare feet standing close up reference photo',
		primarySubject: 'people',
		topic: 'hands-feet',
		sceneTypes: ['close-up'],
		focuses: ['anatomy', 'shape', 'proportion'],
		complexity: 'moderate',
		coverageTags: ['feet', 'body-parts']
	},
	{
		id: 'people-feet-tying-shoes',
		label: 'Tying shoes',
		query: 'person tying shoes hands feet reference photo',
		primarySubject: 'people',
		topic: 'hands-feet',
		secondarySubjects: ['objects'],
		sceneTypes: ['everyday-life', 'close-up'],
		focuses: ['gesture', 'construction', 'negative-space'],
		complexity: 'complex',
		coverageTags: ['hands', 'feet', 'mundane']
	},
	{
		id: 'people-clothing-jacket-folds',
		label: 'Jacket folds on figure',
		query: 'person wearing jacket clothing folds reference photo',
		primarySubject: 'people',
		topic: 'clothing-drapery',
		sceneTypes: ['everyday-life'],
		focuses: ['shape', 'material', 'texture'],
		complexity: 'complex',
		orientation: 'portrait',
		coverageTags: ['fabric', 'material-study']
	},
	{
		id: 'people-clothing-long-coat',
		label: 'Long coat drapery',
		query: 'person wearing long coat fabric folds reference photo',
		primarySubject: 'people',
		topic: 'clothing-drapery',
		focuses: ['gesture', 'shape', 'material'],
		complexity: 'complex',
		orientation: 'portrait',
		coverageTags: ['fabric', 'gesture']
	},
	{
		id: 'people-clothing-sleeves-hands',
		label: 'Sleeves and hands',
		query: 'sleeves hands clothing folds close up reference photo',
		primarySubject: 'people',
		topic: 'clothing-drapery',
		secondarySubjects: ['objects'],
		sceneTypes: ['close-up', 'everyday-life'],
		focuses: ['material', 'texture', 'shape'],
		complexity: 'moderate',
		coverageTags: ['fabric', 'hands', 'material-study']
	},
	{
		id: 'people-groups-waiting-line',
		label: 'People waiting in line',
		query: 'people waiting in line everyday reference photo',
		primarySubject: 'people',
		topic: 'groups-crowds',
		secondarySubjects: ['places'],
		sceneTypes: ['public-space', 'everyday-life'],
		focuses: ['gesture', 'composition', 'proportion'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['groups', 'mundane', 'public-space']
	},
	{
		id: 'people-groups-cafe-table',
		label: 'Small group at table',
		query: 'people sitting around cafe table reference photo',
		primarySubject: 'people',
		topic: 'groups-crowds',
		secondarySubjects: ['objects', 'places'],
		sceneTypes: ['public-space', 'interior', 'everyday-life'],
		focuses: ['composition', 'perspective', 'gesture'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['groups', 'interior', 'mundane']
	},
	{
		id: 'people-groups-transit-riders',
		label: 'Transit riders',
		query: 'people riding public transit interior reference photo',
		primarySubject: 'people',
		topic: 'groups-crowds',
		secondarySubjects: ['vehicles-machines', 'places'],
		sceneTypes: ['public-space', 'interior', 'everyday-life'],
		focuses: ['composition', 'perspective', 'negative-space'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['groups', 'transit', 'mundane']
	}
] satisfies readonly ReferenceSearchSeed[];

const animalSeeds = [
	{
		id: 'animals-pets-cat-sleeping',
		label: 'Sleeping cat',
		query: 'sleeping cat curled pose reference photo',
		primarySubject: 'animals',
		topic: 'pets',
		sceneTypes: ['isolated-subject', 'everyday-life'],
		focuses: ['gesture', 'shape', 'texture'],
		complexity: 'moderate',
		coverageTags: ['organic-form', 'mundane']
	},
	{
		id: 'animals-pets-dog-sitting',
		label: 'Sitting dog',
		query: 'dog sitting pose full body reference photo',
		primarySubject: 'animals',
		topic: 'pets',
		sceneTypes: ['isolated-subject'],
		focuses: ['proportion', 'construction', 'gesture'],
		complexity: 'moderate',
		coverageTags: ['organic-form', 'construction-practice']
	},
	{
		id: 'animals-pets-playing',
		label: 'Pet playing motion',
		query: 'cat dog playing motion reference photo',
		primarySubject: 'animals',
		topic: 'pets',
		focuses: ['gesture', 'shape', 'proportion'],
		complexity: 'complex',
		coverageTags: ['animal-motion', 'gesture']
	},
	{
		id: 'animals-wildlife-deer-standing',
		label: 'Standing deer',
		query: 'deer standing full body wildlife reference photo',
		primarySubject: 'animals',
		topic: 'wildlife',
		sceneTypes: ['landscape', 'isolated-subject'],
		focuses: ['proportion', 'gesture', 'construction'],
		complexity: 'moderate',
		coverageTags: ['organic-form', 'landscape']
	},
	{
		id: 'animals-wildlife-fox-crouch',
		label: 'Fox crouching',
		query: 'fox crouching wildlife pose reference photo',
		primarySubject: 'animals',
		topic: 'wildlife',
		focuses: ['gesture', 'shape', 'texture'],
		complexity: 'moderate',
		coverageTags: ['organic-form', 'gesture']
	},
	{
		id: 'animals-wildlife-large-mammal',
		label: 'Large mammal form',
		query: 'large mammal standing side view reference photo',
		primarySubject: 'animals',
		topic: 'wildlife',
		focuses: ['construction', 'proportion', 'value'],
		complexity: 'complex',
		coverageTags: ['organic-form', 'construction-practice']
	},
	{
		id: 'animals-birds-perched',
		label: 'Perched bird',
		query: 'bird perched branch reference photo',
		primarySubject: 'animals',
		topic: 'birds',
		secondarySubjects: ['nature'],
		sceneTypes: ['isolated-subject'],
		focuses: ['shape', 'proportion', 'texture'],
		complexity: 'moderate',
		coverageTags: ['organic-form', 'negative-space']
	},
	{
		id: 'animals-birds-flying',
		label: 'Bird in flight',
		query: 'bird flying wings spread reference photo',
		primarySubject: 'animals',
		topic: 'birds',
		focuses: ['gesture', 'shape', 'negative-space'],
		complexity: 'moderate',
		coverageTags: ['animal-motion', 'negative-space']
	},
	{
		id: 'animals-birds-water-bird',
		label: 'Water bird',
		query: 'duck heron water bird reference photo',
		primarySubject: 'animals',
		topic: 'birds',
		secondarySubjects: ['nature'],
		sceneTypes: ['landscape'],
		focuses: ['shape', 'value', 'composition'],
		complexity: 'complex',
		coverageTags: ['organic-form', 'water']
	},
	{
		id: 'animals-small-frog',
		label: 'Frog or toad',
		query: 'frog close up body reference photo',
		primarySubject: 'animals',
		topic: 'insects-small-animals',
		sceneTypes: ['close-up'],
		focuses: ['shape', 'texture', 'construction'],
		complexity: 'moderate',
		coverageTags: ['organic-form', 'texture-study']
	},
	{
		id: 'animals-small-lizard',
		label: 'Lizard body',
		query: 'lizard body close up reference photo',
		primarySubject: 'animals',
		topic: 'insects-small-animals',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'texture', 'proportion'],
		complexity: 'complex',
		coverageTags: ['organic-form', 'texture-study']
	},
	{
		id: 'animals-small-insect',
		label: 'Insect close-up',
		query: 'insect close up legs wings reference photo',
		primarySubject: 'animals',
		topic: 'insects-small-animals',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'texture', 'negative-space'],
		complexity: 'dense',
		coverageTags: ['animal-detail', 'negative-space']
	},
	{
		id: 'animals-head-dog-cat',
		label: 'Pet head close-up',
		query: 'dog cat head close up reference photo',
		primarySubject: 'animals',
		topic: 'animal-heads',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'value', 'texture'],
		complexity: 'moderate',
		coverageTags: ['animal-detail', 'texture-study']
	},
	{
		id: 'animals-head-horse-cow',
		label: 'Large animal head',
		query: 'horse cow head profile reference photo',
		primarySubject: 'animals',
		topic: 'animal-heads',
		sceneTypes: ['close-up'],
		focuses: ['proportion', 'construction', 'shape'],
		complexity: 'moderate',
		coverageTags: ['animal-detail', 'construction-practice']
	},
	{
		id: 'animals-details-paws-claws',
		label: 'Paws and claws',
		query: 'animal paws claws close up reference photo',
		primarySubject: 'animals',
		topic: 'paws-details',
		sceneTypes: ['close-up'],
		focuses: ['anatomy', 'shape', 'texture'],
		complexity: 'moderate',
		coverageTags: ['animal-detail', 'body-parts']
	},
	{
		id: 'animals-details-hooves-fur',
		label: 'Hooves and fur detail',
		query: 'animal hooves fur texture detail reference photo',
		primarySubject: 'animals',
		topic: 'paws-details',
		sceneTypes: ['close-up'],
		focuses: ['texture', 'material', 'value'],
		complexity: 'complex',
		coverageTags: ['animal-detail', 'texture-study', 'material-study']
	},
	{
		id: 'animals-motion-running-dog',
		label: 'Running dog',
		query: 'dog running motion full body reference photo',
		primarySubject: 'animals',
		topic: 'motion-poses',
		focuses: ['gesture', 'proportion', 'anatomy'],
		complexity: 'moderate',
		coverageTags: ['animal-motion', 'gesture']
	},
	{
		id: 'animals-motion-jumping-cat',
		label: 'Jumping cat',
		query: 'cat jumping motion pose reference photo',
		primarySubject: 'animals',
		topic: 'motion-poses',
		focuses: ['gesture', 'shape', 'negative-space'],
		complexity: 'complex',
		coverageTags: ['animal-motion', 'negative-space']
	},
	{
		id: 'animals-motion-bird-takeoff',
		label: 'Bird takeoff motion',
		query: 'bird taking off motion wings reference photo',
		primarySubject: 'animals',
		topic: 'motion-poses',
		focuses: ['gesture', 'composition', 'shape'],
		complexity: 'complex',
		coverageTags: ['animal-motion', 'gesture']
	}
] satisfies readonly ReferenceSearchSeed[];

const objectSeeds = [
	{
		id: 'objects-household-lamp-chair',
		label: 'Lamp and chair',
		query: 'ordinary lamp chair household objects reference photo',
		primarySubject: 'objects',
		topic: 'household-objects',
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['construction', 'perspective', 'shape'],
		complexity: 'moderate',
		coverageTags: ['everyday-object', 'mundane', 'interior']
	},
	{
		id: 'objects-household-keys-wallet',
		label: 'Keys and wallet',
		query: 'keys wallet everyday objects table reference photo',
		primarySubject: 'objects',
		topic: 'household-objects',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['shape', 'value', 'negative-space'],
		complexity: 'moderate',
		coverageTags: ['everyday-object', 'still-life', 'negative-space']
	},
	{
		id: 'objects-household-kettle-appliance',
		label: 'Small appliance',
		query: 'kettle toaster small appliance kitchen reference photo',
		primarySubject: 'objects',
		topic: 'household-objects',
		secondarySubjects: ['places'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['construction', 'material', 'value'],
		complexity: 'moderate',
		coverageTags: ['everyday-object', 'kitchen', 'material-study']
	},
	{
		id: 'objects-still-life-mug-bottle',
		label: 'Mug and bottle',
		query: 'mug bottle tabletop still life reference photo',
		primarySubject: 'objects',
		topic: 'still-life-groups',
		sceneTypes: ['still-life'],
		focuses: ['construction', 'shape', 'value'],
		complexity: 'moderate',
		coverageTags: ['still-life', 'construction-practice']
	},
	{
		id: 'objects-still-life-bowl-fruit-cloth',
		label: 'Bowl, fruit, and cloth',
		query: 'bowl fruit cloth still life reference photo',
		primarySubject: 'objects',
		topic: 'still-life-groups',
		sceneTypes: ['still-life'],
		focuses: ['composition', 'value', 'material'],
		complexity: 'complex',
		coverageTags: ['still-life', 'fabric', 'food']
	},
	{
		id: 'objects-still-life-asymmetrical',
		label: 'Asymmetrical still life',
		query: 'asymmetrical tabletop objects still life reference photo',
		primarySubject: 'objects',
		topic: 'still-life-groups',
		sceneTypes: ['still-life'],
		focuses: ['composition', 'negative-space', 'shape'],
		complexity: 'complex',
		coverageTags: ['still-life', 'negative-space']
	},
	{
		id: 'objects-tools-hand-tools',
		label: 'Hand tools on table',
		query: 'hand tools on table reference photo',
		primarySubject: 'objects',
		topic: 'tools',
		sceneTypes: ['still-life', 'workplace'],
		focuses: ['construction', 'perspective', 'material'],
		complexity: 'complex',
		coverageTags: ['material-study', 'construction-practice']
	},
	{
		id: 'objects-tools-garden-tools',
		label: 'Garden tools',
		query: 'garden tools leaning reference photo',
		primarySubject: 'objects',
		topic: 'tools',
		secondarySubjects: ['nature'],
		sceneTypes: ['workplace', 'everyday-life'],
		focuses: ['shape', 'perspective', 'texture'],
		complexity: 'complex',
		coverageTags: ['everyday-object', 'texture-study']
	},
	{
		id: 'objects-tools-art-supplies',
		label: 'Art supplies',
		query: 'drawing painting tools art supplies desk reference photo',
		primarySubject: 'objects',
		topic: 'tools',
		secondarySubjects: ['places'],
		sceneTypes: ['still-life', 'workplace'],
		focuses: ['composition', 'shape', 'material'],
		complexity: 'dense',
		coverageTags: ['desk', 'clutter', 'material-study']
	},
	{
		id: 'objects-food-plate-meal',
		label: 'Ordinary plate of food',
		query: 'ordinary plate of food table reference photo',
		primarySubject: 'objects',
		topic: 'food',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['shape', 'texture', 'value'],
		complexity: 'moderate',
		coverageTags: ['food', 'mundane', 'still-life']
	},
	{
		id: 'objects-food-groceries',
		label: 'Groceries on counter',
		query: 'groceries on kitchen counter reference photo',
		primarySubject: 'objects',
		topic: 'food',
		secondarySubjects: ['places'],
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['composition', 'shape', 'texture'],
		complexity: 'complex',
		coverageTags: ['food', 'kitchen', 'mundane']
	},
	{
		id: 'objects-food-bread-vegetables',
		label: 'Bread and vegetables',
		query: 'bread vegetables cutting board reference photo',
		primarySubject: 'objects',
		topic: 'food',
		sceneTypes: ['still-life'],
		focuses: ['texture', 'value', 'material'],
		complexity: 'complex',
		coverageTags: ['food', 'texture-study', 'material-study']
	},
	{
		id: 'objects-fabric-laundry-pile',
		label: 'Laundry pile',
		query: 'laundry pile fabric folds reference photo',
		primarySubject: 'objects',
		topic: 'fabric-clothing',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['material', 'texture', 'value'],
		complexity: 'complex',
		coverageTags: ['fabric', 'mundane', 'material-study']
	},
	{
		id: 'objects-fabric-folded-towels',
		label: 'Folded towels',
		query: 'folded towels fabric stack reference photo',
		primarySubject: 'objects',
		topic: 'fabric-clothing',
		sceneTypes: ['still-life'],
		focuses: ['shape', 'material', 'light-shadow'],
		complexity: 'moderate',
		coverageTags: ['fabric', 'material-study']
	},
	{
		id: 'objects-fabric-hanging-clothes',
		label: 'Hanging clothes',
		query: 'hanging clothes closet fabric folds reference photo',
		primarySubject: 'objects',
		topic: 'fabric-clothing',
		secondarySubjects: ['places'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['composition', 'shape', 'texture'],
		complexity: 'dense',
		coverageTags: ['fabric', 'interior', 'clutter']
	},
	{
		id: 'objects-books-shelf',
		label: 'Bookshelf',
		query: 'bookshelf books everyday interior reference photo',
		primarySubject: 'objects',
		topic: 'books-electronics',
		secondarySubjects: ['places'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'dense',
		coverageTags: ['interior', 'clutter', 'perspective-practice']
	},
	{
		id: 'objects-electronics-laptop-cables',
		label: 'Laptop and cables',
		query: 'laptop cables desk electronics reference photo',
		primarySubject: 'objects',
		topic: 'books-electronics',
		secondarySubjects: ['places'],
		sceneTypes: ['workplace', 'everyday-life'],
		focuses: ['perspective', 'construction', 'negative-space'],
		complexity: 'complex',
		coverageTags: ['desk', 'clutter', 'negative-space']
	},
	{
		id: 'objects-electronics-phone-hand',
		label: 'Phone and hand',
		query: 'phone in hand everyday reference photo',
		primarySubject: 'objects',
		topic: 'books-electronics',
		secondarySubjects: ['people'],
		sceneTypes: ['close-up', 'everyday-life'],
		focuses: ['shape', 'construction', 'material'],
		complexity: 'moderate',
		coverageTags: ['hands', 'everyday-object', 'material-study']
	},
	{
		id: 'objects-containers-jars-bottles',
		label: 'Jars and bottles',
		query: 'jars bottles containers shelf reference photo',
		primarySubject: 'objects',
		topic: 'containers',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['construction', 'value', 'material'],
		complexity: 'complex',
		coverageTags: ['still-life', 'material-study']
	},
	{
		id: 'objects-containers-boxes-bags',
		label: 'Boxes and bags',
		query: 'cardboard boxes bags containers reference photo',
		primarySubject: 'objects',
		topic: 'containers',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['perspective', 'construction', 'shape'],
		complexity: 'moderate',
		coverageTags: ['everyday-object', 'perspective-practice']
	},
	{
		id: 'objects-clutter-junk-drawer',
		label: 'Junk drawer',
		query: 'open junk drawer clutter reference photo',
		primarySubject: 'objects',
		topic: 'clutter',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['composition', 'shape', 'negative-space'],
		complexity: 'dense',
		coverageTags: ['clutter', 'mundane', 'negative-space']
	},
	{
		id: 'objects-clutter-messy-shelf',
		label: 'Messy shelf',
		query: 'messy shelf household clutter reference photo',
		primarySubject: 'objects',
		topic: 'clutter',
		secondarySubjects: ['places'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['composition', 'perspective', 'value'],
		complexity: 'dense',
		coverageTags: ['clutter', 'interior', 'mundane']
	},
	{
		id: 'objects-clutter-bedside-table',
		label: 'Bedside table clutter',
		query: 'bedside table clutter everyday reference photo',
		primarySubject: 'objects',
		topic: 'clutter',
		secondarySubjects: ['places'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['composition', 'shape', 'value'],
		complexity: 'complex',
		coverageTags: ['clutter', 'interior', 'mundane']
	},
	{
		id: 'objects-clutter-desk-papers',
		label: 'Desk papers clutter',
		query: 'desk papers clutter workspace reference photo',
		primarySubject: 'objects',
		topic: 'clutter',
		secondarySubjects: ['places'],
		sceneTypes: ['workplace', 'everyday-life'],
		focuses: ['perspective', 'composition', 'negative-space'],
		complexity: 'dense',
		coverageTags: ['clutter', 'desk', 'mundane']
	}
] satisfies readonly ReferenceSearchSeed[];

const placeSeeds = [
	{
		id: 'places-rooms-bedroom-corner',
		label: 'Bedroom corner',
		query: 'ordinary bedroom corner interior reference photo',
		primarySubject: 'places',
		topic: 'rooms',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['interior', 'mundane', 'perspective-practice']
	},
	{
		id: 'places-rooms-living-room',
		label: 'Living room',
		query: 'lived in living room interior reference photo',
		primarySubject: 'places',
		topic: 'rooms',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'composition', 'shape'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['interior', 'mundane', 'clutter']
	},
	{
		id: 'places-rooms-door-window',
		label: 'Door and window wall',
		query: 'room wall door window interior reference photo',
		primarySubject: 'places',
		topic: 'rooms',
		sceneTypes: ['interior'],
		focuses: ['perspective', 'construction', 'light-shadow'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['interior', 'perspective-practice', 'architecture']
	},
	{
		id: 'places-rooms-small-apartment',
		label: 'Small apartment room',
		query: 'small apartment room everyday interior reference photo',
		primarySubject: 'places',
		topic: 'rooms',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['composition', 'perspective', 'negative-space'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['interior', 'mundane', 'negative-space']
	},
	{
		id: 'places-kitchen-counter',
		label: 'Kitchen counter',
		query: 'ordinary kitchen counter everyday objects reference photo',
		primarySubject: 'places',
		topic: 'kitchens-workspaces',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'shape', 'value'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['kitchen', 'interior', 'mundane']
	},
	{
		id: 'places-workspace-cluttered-desk',
		label: 'Cluttered desk workspace',
		query: 'cluttered desk workspace reference photo',
		primarySubject: 'places',
		topic: 'kitchens-workspaces',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'workplace', 'everyday-life'],
		focuses: ['perspective', 'composition', 'shape'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['desk', 'clutter', 'mundane']
	},
	{
		id: 'places-workspace-workbench',
		label: 'Workbench',
		query: 'workbench tools garage workspace reference photo',
		primarySubject: 'places',
		topic: 'kitchens-workspaces',
		secondarySubjects: ['objects'],
		sceneTypes: ['workplace', 'interior'],
		focuses: ['perspective', 'material', 'composition'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['desk', 'clutter', 'material-study']
	},
	{
		id: 'places-kitchen-sink-dishes',
		label: 'Kitchen sink dishes',
		query: 'kitchen sink dishes everyday reference photo',
		primarySubject: 'places',
		topic: 'kitchens-workspaces',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['composition', 'value', 'material'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['kitchen', 'mundane', 'clutter']
	},
	{
		id: 'places-public-cafe-interior',
		label: 'Café interior',
		query: 'ordinary cafe interior tables reference photo',
		primarySubject: 'places',
		topic: 'public-interiors',
		secondarySubjects: ['people', 'objects'],
		sceneTypes: ['interior', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['interior', 'public-space', 'mundane']
	},
	{
		id: 'places-public-laundromat',
		label: 'Laundromat',
		query: 'laundromat interior everyday reference photo',
		primarySubject: 'places',
		topic: 'public-interiors',
		secondarySubjects: ['people', 'objects'],
		sceneTypes: ['interior', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'construction', 'composition'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['interior', 'mundane', 'public-space']
	},
	{
		id: 'places-public-waiting-room',
		label: 'Waiting room',
		query: 'waiting room chairs interior reference photo',
		primarySubject: 'places',
		topic: 'public-interiors',
		secondarySubjects: ['people', 'objects'],
		sceneTypes: ['interior', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'negative-space'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['interior', 'public-space', 'negative-space']
	},
	{
		id: 'places-street-sidewalk-row',
		label: 'Sidewalk block',
		query: 'ordinary sidewalk street buildings reference photo',
		primarySubject: 'places',
		topic: 'streets-sidewalks',
		secondarySubjects: ['people', 'vehicles-machines'],
		sceneTypes: ['street', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['street', 'perspective-practice', 'mundane']
	},
	{
		id: 'places-street-alley',
		label: 'Alley perspective',
		query: 'alley street perspective everyday reference photo',
		primarySubject: 'places',
		topic: 'streets-sidewalks',
		sceneTypes: ['street', 'public-space'],
		focuses: ['perspective', 'composition', 'light-shadow'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['street', 'perspective-practice']
	},
	{
		id: 'places-street-intersection',
		label: 'Street intersection',
		query: 'street intersection crosswalk everyday reference photo',
		primarySubject: 'places',
		topic: 'streets-sidewalks',
		secondarySubjects: ['people', 'vehicles-machines'],
		sceneTypes: ['street', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'shape'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['street', 'public-space', 'vehicle']
	},
	{
		id: 'places-storefront-small-shop',
		label: 'Small shop storefront',
		query: 'small shop storefront sidewalk reference photo',
		primarySubject: 'places',
		topic: 'storefronts',
		secondarySubjects: ['objects'],
		sceneTypes: ['street', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['storefront', 'street', 'architecture']
	},
	{
		id: 'places-storefront-window-display',
		label: 'Window display',
		query: 'store window display reflections reference photo',
		primarySubject: 'places',
		topic: 'storefronts',
		secondarySubjects: ['objects'],
		sceneTypes: ['street', 'public-space'],
		focuses: ['composition', 'material', 'value'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['storefront', 'material-study']
	},
	{
		id: 'places-storefront-market-stall',
		label: 'Market stall',
		query: 'market stall storefront goods reference photo',
		primarySubject: 'places',
		topic: 'storefronts',
		secondarySubjects: ['people', 'objects'],
		sceneTypes: ['public-space', 'street', 'everyday-life'],
		focuses: ['composition', 'shape', 'perspective'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['storefront', 'clutter', 'public-space']
	},
	{
		id: 'places-transit-bus-stop',
		label: 'Bus stop',
		query: 'bus stop people waiting street reference photo',
		primarySubject: 'places',
		topic: 'transit-stops',
		secondarySubjects: ['people', 'vehicles-machines'],
		sceneTypes: ['street', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'gesture'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['transit', 'street', 'mundane']
	},
	{
		id: 'places-transit-train-platform',
		label: 'Train platform',
		query: 'train platform station perspective reference photo',
		primarySubject: 'places',
		topic: 'transit-stops',
		secondarySubjects: ['people', 'vehicles-machines'],
		sceneTypes: ['public-space', 'street'],
		focuses: ['perspective', 'composition', 'construction'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['transit', 'perspective-practice', 'vehicle']
	},
	{
		id: 'places-transit-station-interior',
		label: 'Transit station interior',
		query: 'subway station interior people reference photo',
		primarySubject: 'places',
		topic: 'transit-stops',
		secondarySubjects: ['people', 'vehicles-machines'],
		sceneTypes: ['public-space', 'interior', 'everyday-life'],
		focuses: ['perspective', 'composition', 'light-shadow'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['transit', 'interior', 'public-space']
	},
	{
		id: 'places-parking-lot-cars',
		label: 'Parking lot with cars',
		query: 'parking lot parked cars everyday reference photo',
		primarySubject: 'places',
		topic: 'parking-lots',
		secondarySubjects: ['vehicles-machines'],
		sceneTypes: ['street', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'shape'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'perspective-practice', 'mundane']
	},
	{
		id: 'places-parking-garage',
		label: 'Parking garage',
		query: 'parking garage perspective reference photo',
		primarySubject: 'places',
		topic: 'parking-lots',
		secondarySubjects: ['vehicles-machines'],
		sceneTypes: ['public-space'],
		focuses: ['perspective', 'light-shadow', 'composition'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'perspective-practice']
	},
	{
		id: 'places-stairs-apartment',
		label: 'Apartment stairwell',
		query: 'apartment stairwell interior perspective reference photo',
		primarySubject: 'places',
		topic: 'stairs-corridors',
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'construction', 'value'],
		complexity: 'complex',
		orientation: 'portrait',
		coverageTags: ['interior', 'perspective-practice', 'architecture']
	},
	{
		id: 'places-corridor-hallway',
		label: 'Hallway corridor',
		query: 'ordinary hallway corridor perspective reference photo',
		primarySubject: 'places',
		topic: 'stairs-corridors',
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'composition', 'negative-space'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['interior', 'perspective-practice', 'negative-space']
	},
	{
		id: 'places-architecture-house-front',
		label: 'House front',
		query: 'ordinary house front facade reference photo',
		primarySubject: 'places',
		topic: 'architecture-facades',
		sceneTypes: ['street', 'everyday-life'],
		focuses: ['perspective', 'construction', 'shape'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['architecture', 'perspective-practice', 'mundane']
	},
	{
		id: 'places-architecture-apartment-facade',
		label: 'Apartment façade',
		query: 'apartment building facade windows reference photo',
		primarySubject: 'places',
		topic: 'architecture-facades',
		sceneTypes: ['street'],
		focuses: ['perspective', 'composition', 'construction'],
		complexity: 'dense',
		orientation: 'portrait',
		coverageTags: ['architecture', 'perspective-practice']
	},
	{
		id: 'places-architecture-door-detail',
		label: 'Doorway detail',
		query: 'building doorway architectural detail reference photo',
		primarySubject: 'places',
		topic: 'architecture-facades',
		sceneTypes: ['street', 'close-up'],
		focuses: ['construction', 'material', 'texture'],
		complexity: 'complex',
		orientation: 'portrait',
		coverageTags: ['architecture', 'material-study', 'texture-study']
	}
] satisfies readonly ReferenceSearchSeed[];

const natureSeeds = [
	{
		id: 'nature-plants-potted-window',
		label: 'Potted plant by window',
		query: 'potted plant by window reference photo',
		primarySubject: 'nature',
		topic: 'plants-flowers',
		secondarySubjects: ['places'],
		sceneTypes: ['isolated-subject', 'interior'],
		focuses: ['shape', 'texture', 'negative-space'],
		complexity: 'moderate',
		coverageTags: ['plant', 'organic-form', 'negative-space']
	},
	{
		id: 'nature-plants-weeds-leaves',
		label: 'Weeds and leaves',
		query: 'weeds leaves close up organic forms reference photo',
		primarySubject: 'nature',
		topic: 'plants-flowers',
		sceneTypes: ['close-up'],
		focuses: ['gesture', 'shape', 'texture'],
		complexity: 'complex',
		coverageTags: ['plant', 'organic-form', 'texture-study']
	},
	{
		id: 'nature-plants-bouquet-flowers',
		label: 'Bouquet flowers',
		query: 'bouquet flowers vase reference photo',
		primarySubject: 'nature',
		topic: 'plants-flowers',
		secondarySubjects: ['objects'],
		sceneTypes: ['still-life'],
		focuses: ['composition', 'shape', 'value'],
		complexity: 'dense',
		coverageTags: ['plant', 'still-life', 'organic-form']
	},
	{
		id: 'nature-trees-bare-branches',
		label: 'Bare branches',
		query: 'bare tree branches negative space reference photo',
		primarySubject: 'nature',
		topic: 'trees-branches',
		focuses: ['gesture', 'negative-space', 'shape'],
		complexity: 'complex',
		coverageTags: ['plant', 'negative-space', 'organic-form']
	},
	{
		id: 'nature-trees-leafy-mass',
		label: 'Leafy tree mass',
		query: 'leafy tree canopy light shadow reference photo',
		primarySubject: 'nature',
		topic: 'trees-branches',
		sceneTypes: ['landscape'],
		focuses: ['value', 'texture', 'shape'],
		complexity: 'dense',
		coverageTags: ['plant', 'texture-study', 'landscape']
	},
	{
		id: 'nature-trees-trunk-roots',
		label: 'Tree trunk and roots',
		query: 'tree trunk roots texture reference photo',
		primarySubject: 'nature',
		topic: 'trees-branches',
		sceneTypes: ['close-up', 'landscape'],
		focuses: ['texture', 'construction', 'value'],
		complexity: 'complex',
		coverageTags: ['plant', 'texture-study', 'organic-form']
	},
	{
		id: 'nature-rocks-gravel-ground',
		label: 'Gravel and ground',
		query: 'gravel stones ground texture reference photo',
		primarySubject: 'nature',
		topic: 'rocks-ground',
		sceneTypes: ['landscape', 'close-up'],
		focuses: ['texture', 'value', 'shape'],
		complexity: 'dense',
		coverageTags: ['texture-study', 'landscape']
	},
	{
		id: 'nature-rocks-dirt-path',
		label: 'Dirt path rocks',
		query: 'dirt path rocks ground reference photo',
		primarySubject: 'nature',
		topic: 'rocks-ground',
		sceneTypes: ['landscape', 'everyday-life'],
		focuses: ['perspective', 'texture', 'composition'],
		complexity: 'complex',
		coverageTags: ['landscape', 'perspective-practice', 'texture-study']
	},
	{
		id: 'nature-water-river-bank',
		label: 'River bank',
		query: 'river bank landscape reference photo',
		primarySubject: 'nature',
		topic: 'water-coast',
		sceneTypes: ['landscape'],
		focuses: ['composition', 'value', 'shape'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['water', 'landscape']
	},
	{
		id: 'nature-water-beach-shore',
		label: 'Beach shoreline',
		query: 'beach shoreline waves reference photo',
		primarySubject: 'nature',
		topic: 'water-coast',
		sceneTypes: ['landscape'],
		focuses: ['gesture', 'value', 'composition'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['water', 'landscape', 'gesture']
	},
	{
		id: 'nature-water-puddles-street',
		label: 'Puddles and reflections',
		query: 'puddles reflections sidewalk reference photo',
		primarySubject: 'nature',
		topic: 'water-coast',
		secondarySubjects: ['places'],
		sceneTypes: ['street', 'everyday-life'],
		focuses: ['value', 'material', 'composition'],
		complexity: 'complex',
		coverageTags: ['water', 'street', 'material-study']
	},
	{
		id: 'nature-sky-cloudy',
		label: 'Cloudy sky',
		query: 'cloudy sky value study reference photo',
		primarySubject: 'nature',
		topic: 'sky-clouds',
		sceneTypes: ['landscape'],
		focuses: ['value', 'composition', 'shape'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['landscape']
	},
	{
		id: 'nature-sky-storm-clouds',
		label: 'Storm clouds',
		query: 'storm clouds dramatic light reference photo',
		primarySubject: 'nature',
		topic: 'sky-clouds',
		sceneTypes: ['landscape'],
		focuses: ['value', 'light-shadow', 'composition'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['landscape']
	},
	{
		id: 'nature-garden-path-plants',
		label: 'Garden path',
		query: 'garden path plants perspective reference photo',
		primarySubject: 'nature',
		topic: 'gardens-parks',
		secondarySubjects: ['places'],
		sceneTypes: ['landscape', 'everyday-life'],
		focuses: ['perspective', 'composition', 'texture'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['plant', 'landscape', 'perspective-practice']
	},
	{
		id: 'nature-park-bench-trees',
		label: 'Park bench and trees',
		query: 'park bench trees path everyday reference photo',
		primarySubject: 'nature',
		topic: 'gardens-parks',
		secondarySubjects: ['places', 'objects'],
		sceneTypes: ['landscape', 'public-space', 'everyday-life'],
		focuses: ['composition', 'perspective', 'value'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['landscape', 'public-space', 'mundane']
	},
	{
		id: 'nature-park-playground-edge',
		label: 'Park edge with objects',
		query: 'park edge path playground trees reference photo',
		primarySubject: 'nature',
		topic: 'gardens-parks',
		secondarySubjects: ['places', 'objects'],
		sceneTypes: ['landscape', 'public-space', 'everyday-life'],
		focuses: ['composition', 'shape', 'perspective'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['landscape', 'public-space', 'mundane']
	},
	{
		id: 'nature-landscape-field-road',
		label: 'Field road',
		query: 'ordinary rural road field landscape reference photo',
		primarySubject: 'nature',
		topic: 'landscapes',
		sceneTypes: ['landscape', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['landscape', 'perspective-practice', 'mundane']
	},
	{
		id: 'nature-landscape-forest-edge',
		label: 'Forest edge',
		query: 'forest edge trees landscape reference photo',
		primarySubject: 'nature',
		topic: 'landscapes',
		sceneTypes: ['landscape'],
		focuses: ['value', 'composition', 'texture'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['landscape', 'texture-study']
	},
	{
		id: 'nature-landscape-hills',
		label: 'Hills and fields',
		query: 'hills fields landscape composition reference photo',
		primarySubject: 'nature',
		topic: 'landscapes',
		sceneTypes: ['landscape'],
		focuses: ['composition', 'shape', 'value'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['landscape']
	}
] satisfies readonly ReferenceSearchSeed[];

const vehicleMachineSeeds = [
	{
		id: 'vehicles-cars-parked-street',
		label: 'Parked car on street',
		query: 'parked car on street perspective reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'cars-trucks',
		secondarySubjects: ['places'],
		sceneTypes: ['street', 'everyday-life'],
		focuses: ['perspective', 'construction', 'shape'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'street', 'perspective-practice']
	},
	{
		id: 'vehicles-cars-interior-dashboard',
		label: 'Car interior dashboard',
		query: 'car interior dashboard reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'cars-trucks',
		sceneTypes: ['interior', 'close-up'],
		focuses: ['perspective', 'construction', 'material'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'interior', 'mechanical-detail']
	},
	{
		id: 'vehicles-trucks-delivery',
		label: 'Delivery truck',
		query: 'delivery truck parked street reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'cars-trucks',
		secondarySubjects: ['places'],
		sceneTypes: ['street', 'everyday-life'],
		focuses: ['construction', 'perspective', 'value'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'street', 'mundane']
	},
	{
		id: 'vehicles-bikes-bicycle-side',
		label: 'Bicycle side view',
		query: 'bicycle side view reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'bikes-motorcycles',
		sceneTypes: ['isolated-subject', 'street'],
		focuses: ['construction', 'shape', 'negative-space'],
		complexity: 'complex',
		coverageTags: ['vehicle', 'negative-space', 'construction-practice']
	},
	{
		id: 'vehicles-bikes-scooter-parked',
		label: 'Parked scooter',
		query: 'parked scooter street reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'bikes-motorcycles',
		secondarySubjects: ['places'],
		sceneTypes: ['street', 'everyday-life'],
		focuses: ['construction', 'perspective', 'material'],
		complexity: 'complex',
		coverageTags: ['vehicle', 'street', 'material-study']
	},
	{
		id: 'vehicles-bikes-motorcycle-detail',
		label: 'Motorcycle detail',
		query: 'motorcycle engine wheel detail reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'bikes-motorcycles',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'material', 'texture'],
		complexity: 'dense',
		coverageTags: ['vehicle', 'mechanical-detail', 'material-study']
	},
	{
		id: 'vehicles-buses-city-bus',
		label: 'City bus',
		query: 'city bus street perspective reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'buses-trains',
		secondarySubjects: ['places', 'people'],
		sceneTypes: ['street', 'public-space'],
		focuses: ['perspective', 'construction', 'composition'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'transit', 'street']
	},
	{
		id: 'vehicles-trains-platform',
		label: 'Train at platform',
		query: 'train at platform perspective reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'buses-trains',
		secondarySubjects: ['places', 'people'],
		sceneTypes: ['public-space', 'street'],
		focuses: ['perspective', 'construction', 'value'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'transit', 'perspective-practice']
	},
	{
		id: 'vehicles-boats-dock',
		label: 'Boats at dock',
		query: 'boats at dock reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'boats-aircraft',
		secondarySubjects: ['nature', 'places'],
		sceneTypes: ['landscape', 'public-space'],
		focuses: ['perspective', 'composition', 'shape'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'water', 'landscape']
	},
	{
		id: 'vehicles-aircraft-small-plane',
		label: 'Small aircraft',
		query: 'small airplane parked reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'boats-aircraft',
		sceneTypes: ['isolated-subject', 'public-space'],
		focuses: ['construction', 'perspective', 'shape'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'construction-practice']
	},
	{
		id: 'vehicles-construction-excavator',
		label: 'Excavator',
		query: 'excavator construction machinery reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'construction-machinery',
		secondarySubjects: ['places'],
		sceneTypes: ['workplace'],
		focuses: ['construction', 'perspective', 'material'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'mechanical-detail', 'construction-practice']
	},
	{
		id: 'vehicles-construction-tractor-crane',
		label: 'Tractor or crane',
		query: 'tractor crane construction machine reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'construction-machinery',
		sceneTypes: ['workplace', 'public-space'],
		focuses: ['construction', 'shape', 'perspective'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'mechanical-detail']
	},
	{
		id: 'vehicles-mechanical-engine',
		label: 'Engine parts',
		query: 'engine parts mechanical detail reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'mechanical-details',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'material', 'texture'],
		complexity: 'dense',
		coverageTags: ['mechanical-detail', 'material-study', 'texture-study']
	},
	{
		id: 'vehicles-mechanical-gears-pipes',
		label: 'Gears and pipes',
		query: 'gears pipes machinery detail reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'mechanical-details',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'shape', 'negative-space'],
		complexity: 'dense',
		coverageTags: ['mechanical-detail', 'negative-space', 'construction-practice']
	},
	{
		id: 'vehicles-mechanical-control-panel',
		label: 'Control panel',
		query: 'machine control panel buttons reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'mechanical-details',
		sceneTypes: ['close-up', 'workplace'],
		focuses: ['composition', 'shape', 'material'],
		complexity: 'dense',
		coverageTags: ['mechanical-detail', 'material-study']
	}
] satisfies readonly ReferenceSearchSeed[];

export const defaultReferenceSearchSeeds = [
	...peopleSeeds,
	...animalSeeds,
	...objectSeeds,
	...placeSeeds,
	...natureSeeds,
	...vehicleMachineSeeds
] satisfies readonly ReferenceSearchSeed[];
