import type { ReferenceSearchSeed } from '../reference-seed';

export const natureSeeds = [
	{
		id: 'nature-plants-potted-window',
		label: 'Potted plant by window',
		query: 'potted plant by window reference photo',
		primarySubject: 'nature',
		topic: 'plants-flowers',
		secondarySubjects: ['places'],
		sceneTypes: ['isolated-subject', 'interior'],
		focuses: ['shape', 'texture', 'negative-space'],
		complexity: 'moderate',
		coverageTags: ['plant', 'organic-form', 'negative-space']
	},
	{
		id: 'nature-plants-weeds-leaves',
		label: 'Weeds and leaves',
		query: 'weeds leaves close up organic forms reference photo',
		primarySubject: 'nature',
		topic: 'plants-flowers',
		sceneTypes: ['close-up'],
		focuses: ['gesture', 'shape', 'texture'],
		complexity: 'complex',
		coverageTags: ['plant', 'organic-form', 'texture-study']
	},
	{
		id: 'nature-plants-bouquet-flowers',
		label: 'Bouquet flowers',
		query: 'bouquet flowers vase reference photo',
		primarySubject: 'nature',
		topic: 'plants-flowers',
		secondarySubjects: ['objects'],
		sceneTypes: ['still-life'],
		focuses: ['composition', 'shape', 'value'],
		complexity: 'dense',
		coverageTags: ['plant', 'still-life', 'organic-form']
	},
	{
		id: 'nature-trees-bare-branches',
		label: 'Bare branches',
		query: 'bare tree branches negative space reference photo',
		primarySubject: 'nature',
		topic: 'trees-branches',
		focuses: ['gesture', 'negative-space', 'shape'],
		complexity: 'complex',
		coverageTags: ['plant', 'negative-space', 'organic-form']
	},
	{
		id: 'nature-trees-leafy-mass',
		label: 'Leafy tree mass',
		query: 'leafy tree canopy light shadow reference photo',
		primarySubject: 'nature',
		topic: 'trees-branches',
		sceneTypes: ['landscape'],
		focuses: ['value', 'texture', 'shape'],
		complexity: 'dense',
		coverageTags: ['plant', 'texture-study', 'landscape']
	},
	{
		id: 'nature-trees-trunk-roots',
		label: 'Tree trunk and roots',
		query: 'tree trunk roots texture reference photo',
		primarySubject: 'nature',
		topic: 'trees-branches',
		sceneTypes: ['close-up', 'landscape'],
		focuses: ['texture', 'construction', 'value'],
		complexity: 'complex',
		coverageTags: ['plant', 'texture-study', 'organic-form']
	},
	{
		id: 'nature-rocks-gravel-ground',
		label: 'Gravel and ground',
		query: 'gravel stones ground texture reference photo',
		primarySubject: 'nature',
		topic: 'rocks-ground',
		sceneTypes: ['landscape', 'close-up'],
		focuses: ['texture', 'value', 'shape'],
		complexity: 'dense',
		coverageTags: ['texture-study', 'landscape']
	},
	{
		id: 'nature-rocks-dirt-path',
		label: 'Dirt path rocks',
		query: 'dirt path rocks ground reference photo',
		primarySubject: 'nature',
		topic: 'rocks-ground',
		sceneTypes: ['landscape', 'everyday-life'],
		focuses: ['perspective', 'texture', 'composition'],
		complexity: 'complex',
		coverageTags: ['landscape', 'perspective-practice', 'texture-study']
	},
	{
		id: 'nature-water-river-bank',
		label: 'River bank',
		query: 'river bank landscape reference photo',
		primarySubject: 'nature',
		topic: 'water-coast',
		sceneTypes: ['landscape'],
		focuses: ['composition', 'value', 'shape'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['water', 'landscape']
	},
	{
		id: 'nature-water-beach-shore',
		label: 'Beach shoreline',
		query: 'beach shoreline waves reference photo',
		primarySubject: 'nature',
		topic: 'water-coast',
		sceneTypes: ['landscape'],
		focuses: ['gesture', 'value', 'composition'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['water', 'landscape', 'gesture']
	},
	{
		id: 'nature-water-puddles-street',
		label: 'Puddles and reflections',
		query: 'puddles reflections sidewalk reference photo',
		primarySubject: 'nature',
		topic: 'water-coast',
		secondarySubjects: ['places'],
		sceneTypes: ['street', 'everyday-life'],
		focuses: ['value', 'material', 'composition'],
		complexity: 'complex',
		coverageTags: ['water', 'street', 'material-study']
	},
	{
		id: 'nature-sky-cloudy',
		label: 'Cloudy sky',
		query: 'cloudy sky value study reference photo',
		primarySubject: 'nature',
		topic: 'sky-clouds',
		sceneTypes: ['landscape'],
		focuses: ['value', 'composition', 'shape'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['landscape']
	},
	{
		id: 'nature-sky-storm-clouds',
		label: 'Storm clouds',
		query: 'storm clouds dramatic light reference photo',
		primarySubject: 'nature',
		topic: 'sky-clouds',
		sceneTypes: ['landscape'],
		focuses: ['value', 'light-shadow', 'composition'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['landscape']
	},
	{
		id: 'nature-garden-path-plants',
		label: 'Garden path',
		query: 'garden path plants perspective reference photo',
		primarySubject: 'nature',
		topic: 'gardens-parks',
		secondarySubjects: ['places'],
		sceneTypes: ['landscape', 'everyday-life'],
		focuses: ['perspective', 'composition', 'texture'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['plant', 'landscape', 'perspective-practice']
	},
	{
		id: 'nature-park-bench-trees',
		label: 'Park bench and trees',
		query: 'park bench trees path everyday reference photo',
		primarySubject: 'nature',
		topic: 'gardens-parks',
		secondarySubjects: ['places', 'objects'],
		sceneTypes: ['landscape', 'public-space', 'everyday-life'],
		focuses: ['composition', 'perspective', 'value'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['landscape', 'public-space', 'mundane']
	},
	{
		id: 'nature-park-playground-edge',
		label: 'Park edge with objects',
		query: 'park edge path playground trees reference photo',
		primarySubject: 'nature',
		topic: 'gardens-parks',
		secondarySubjects: ['places', 'objects'],
		sceneTypes: ['landscape', 'public-space', 'everyday-life'],
		focuses: ['composition', 'shape', 'perspective'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['landscape', 'public-space', 'mundane']
	},
	{
		id: 'nature-landscape-field-road',
		label: 'Field road',
		query: 'ordinary rural road field landscape reference photo',
		primarySubject: 'nature',
		topic: 'landscapes',
		sceneTypes: ['landscape', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['landscape', 'perspective-practice', 'mundane']
	},
	{
		id: 'nature-landscape-forest-edge',
		label: 'Forest edge',
		query: 'forest edge trees landscape reference photo',
		primarySubject: 'nature',
		topic: 'landscapes',
		sceneTypes: ['landscape'],
		focuses: ['value', 'composition', 'texture'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['landscape', 'texture-study']
	},
	{
		id: 'nature-landscape-hills',
		label: 'Hills and fields',
		query: 'hills fields landscape composition reference photo',
		primarySubject: 'nature',
		topic: 'landscapes',
		sceneTypes: ['landscape'],
		focuses: ['composition', 'shape', 'value'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['landscape']
	}
] satisfies readonly ReferenceSearchSeed[];
