import type { ReferenceSearchSeed } from '../reference-seed';

export const objectSeeds = [
	{
		id: 'objects-household-lamp-chair',
		label: 'Lamp and chair',
		query: 'ordinary lamp chair household objects reference photo',
		primarySubject: 'objects',
		topic: 'household-objects',
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['construction', 'perspective', 'shape'],
		complexity: 'moderate',
		coverageTags: ['everyday-object', 'mundane', 'interior']
	},
	{
		id: 'objects-household-keys-wallet',
		label: 'Keys and wallet',
		query: 'keys wallet everyday objects table reference photo',
		primarySubject: 'objects',
		topic: 'household-objects',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['shape', 'value', 'negative-space'],
		complexity: 'moderate',
		coverageTags: ['everyday-object', 'still-life', 'negative-space']
	},
	{
		id: 'objects-household-kettle-appliance',
		label: 'Small appliance',
		query: 'kettle toaster small appliance kitchen reference photo',
		primarySubject: 'objects',
		topic: 'household-objects',
		secondarySubjects: ['places'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['construction', 'material', 'value'],
		complexity: 'moderate',
		coverageTags: ['everyday-object', 'kitchen', 'material-study']
	},
	{
		id: 'objects-still-life-mug-bottle',
		label: 'Mug and bottle',
		query: 'mug bottle tabletop still life reference photo',
		primarySubject: 'objects',
		topic: 'still-life-groups',
		sceneTypes: ['still-life'],
		focuses: ['construction', 'shape', 'value'],
		complexity: 'moderate',
		coverageTags: ['still-life', 'construction-practice']
	},
	{
		id: 'objects-still-life-bowl-fruit-cloth',
		label: 'Bowl, fruit, and cloth',
		query: 'bowl fruit cloth still life reference photo',
		primarySubject: 'objects',
		topic: 'still-life-groups',
		sceneTypes: ['still-life'],
		focuses: ['composition', 'value', 'material'],
		complexity: 'complex',
		coverageTags: ['still-life', 'fabric', 'food']
	},
	{
		id: 'objects-still-life-asymmetrical',
		label: 'Asymmetrical still life',
		query: 'asymmetrical tabletop objects still life reference photo',
		primarySubject: 'objects',
		topic: 'still-life-groups',
		sceneTypes: ['still-life'],
		focuses: ['composition', 'negative-space', 'shape'],
		complexity: 'complex',
		coverageTags: ['still-life', 'negative-space']
	},
	{
		id: 'objects-tools-hand-tools',
		label: 'Hand tools on table',
		query: 'hand tools on table reference photo',
		primarySubject: 'objects',
		topic: 'tools',
		sceneTypes: ['still-life', 'workplace'],
		focuses: ['construction', 'perspective', 'material'],
		complexity: 'complex',
		coverageTags: ['material-study', 'construction-practice']
	},
	{
		id: 'objects-tools-garden-tools',
		label: 'Garden tools',
		query: 'garden tools leaning reference photo',
		primarySubject: 'objects',
		topic: 'tools',
		secondarySubjects: ['nature'],
		sceneTypes: ['workplace', 'everyday-life'],
		focuses: ['shape', 'perspective', 'texture'],
		complexity: 'complex',
		coverageTags: ['everyday-object', 'texture-study']
	},
	{
		id: 'objects-tools-art-supplies',
		label: 'Art supplies',
		query: 'drawing painting tools art supplies desk reference photo',
		primarySubject: 'objects',
		topic: 'tools',
		secondarySubjects: ['places'],
		sceneTypes: ['still-life', 'workplace'],
		focuses: ['composition', 'shape', 'material'],
		complexity: 'dense',
		coverageTags: ['desk', 'clutter', 'material-study']
	},
	{
		id: 'objects-food-plate-meal',
		label: 'Ordinary plate of food',
		query: 'ordinary plate of food table reference photo',
		primarySubject: 'objects',
		topic: 'food',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['shape', 'texture', 'value'],
		complexity: 'moderate',
		coverageTags: ['food', 'mundane', 'still-life']
	},
	{
		id: 'objects-food-groceries',
		label: 'Groceries on counter',
		query: 'groceries on kitchen counter reference photo',
		primarySubject: 'objects',
		topic: 'food',
		secondarySubjects: ['places'],
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['composition', 'shape', 'texture'],
		complexity: 'complex',
		coverageTags: ['food', 'kitchen', 'mundane']
	},
	{
		id: 'objects-food-bread-vegetables',
		label: 'Bread and vegetables',
		query: 'bread vegetables cutting board reference photo',
		primarySubject: 'objects',
		topic: 'food',
		sceneTypes: ['still-life'],
		focuses: ['texture', 'value', 'material'],
		complexity: 'complex',
		coverageTags: ['food', 'texture-study', 'material-study']
	},
	{
		id: 'objects-fabric-laundry-pile',
		label: 'Laundry pile',
		query: 'laundry pile fabric folds reference photo',
		primarySubject: 'objects',
		topic: 'fabric-clothing',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['material', 'texture', 'value'],
		complexity: 'complex',
		coverageTags: ['fabric', 'mundane', 'material-study']
	},
	{
		id: 'objects-fabric-folded-towels',
		label: 'Folded towels',
		query: 'folded towels fabric stack reference photo',
		primarySubject: 'objects',
		topic: 'fabric-clothing',
		sceneTypes: ['still-life'],
		focuses: ['shape', 'material', 'light-shadow'],
		complexity: 'moderate',
		coverageTags: ['fabric', 'material-study']
	},
	{
		id: 'objects-fabric-hanging-clothes',
		label: 'Hanging clothes',
		query: 'hanging clothes closet fabric folds reference photo',
		primarySubject: 'objects',
		topic: 'fabric-clothing',
		secondarySubjects: ['places'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['composition', 'shape', 'texture'],
		complexity: 'dense',
		coverageTags: ['fabric', 'interior', 'clutter']
	},
	{
		id: 'objects-books-shelf',
		label: 'Bookshelf',
		query: 'bookshelf books everyday interior reference photo',
		primarySubject: 'objects',
		topic: 'books-electronics',
		secondarySubjects: ['places'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'dense',
		coverageTags: ['interior', 'clutter', 'perspective-practice']
	},
	{
		id: 'objects-electronics-laptop-cables',
		label: 'Laptop and cables',
		query: 'laptop cables desk electronics reference photo',
		primarySubject: 'objects',
		topic: 'books-electronics',
		secondarySubjects: ['places'],
		sceneTypes: ['workplace', 'everyday-life'],
		focuses: ['perspective', 'construction', 'negative-space'],
		complexity: 'complex',
		coverageTags: ['desk', 'clutter', 'negative-space']
	},
	{
		id: 'objects-electronics-phone-hand',
		label: 'Phone and hand',
		query: 'phone in hand everyday reference photo',
		primarySubject: 'objects',
		topic: 'books-electronics',
		secondarySubjects: ['people'],
		sceneTypes: ['close-up', 'everyday-life'],
		focuses: ['shape', 'construction', 'material'],
		complexity: 'moderate',
		coverageTags: ['hands', 'everyday-object', 'material-study']
	},
	{
		id: 'objects-containers-jars-bottles',
		label: 'Jars and bottles',
		query: 'jars bottles containers shelf reference photo',
		primarySubject: 'objects',
		topic: 'containers',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['construction', 'value', 'material'],
		complexity: 'complex',
		coverageTags: ['still-life', 'material-study']
	},
	{
		id: 'objects-containers-boxes-bags',
		label: 'Boxes and bags',
		query: 'cardboard boxes bags containers reference photo',
		primarySubject: 'objects',
		topic: 'containers',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['perspective', 'construction', 'shape'],
		complexity: 'moderate',
		coverageTags: ['everyday-object', 'perspective-practice']
	},
	{
		id: 'objects-clutter-junk-drawer',
		label: 'Junk drawer',
		query: 'open junk drawer clutter reference photo',
		primarySubject: 'objects',
		topic: 'clutter',
		sceneTypes: ['still-life', 'everyday-life'],
		focuses: ['composition', 'shape', 'negative-space'],
		complexity: 'dense',
		coverageTags: ['clutter', 'mundane', 'negative-space']
	},
	{
		id: 'objects-clutter-messy-shelf',
		label: 'Messy shelf',
		query: 'messy shelf household clutter reference photo',
		primarySubject: 'objects',
		topic: 'clutter',
		secondarySubjects: ['places'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['composition', 'perspective', 'value'],
		complexity: 'dense',
		coverageTags: ['clutter', 'interior', 'mundane']
	},
	{
		id: 'objects-clutter-bedside-table',
		label: 'Bedside table clutter',
		query: 'bedside table clutter everyday reference photo',
		primarySubject: 'objects',
		topic: 'clutter',
		secondarySubjects: ['places'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['composition', 'shape', 'value'],
		complexity: 'complex',
		coverageTags: ['clutter', 'interior', 'mundane']
	},
	{
		id: 'objects-clutter-desk-papers',
		label: 'Desk papers clutter',
		query: 'desk papers clutter workspace reference photo',
		primarySubject: 'objects',
		topic: 'clutter',
		secondarySubjects: ['places'],
		sceneTypes: ['workplace', 'everyday-life'],
		focuses: ['perspective', 'composition', 'negative-space'],
		complexity: 'dense',
		coverageTags: ['clutter', 'desk', 'mundane']
	}
] satisfies readonly ReferenceSearchSeed[];
