import type { ReferenceSearchSeed } from '../reference-seed';

export const peopleSeeds = [
	{
		id: 'people-gesture-walking-stride',
		label: 'Walking stride gesture',
		query: 'person walking full body gesture reference photo',
		primarySubject: 'people',
		topic: 'gesture-action',
		sceneTypes: ['everyday-life'],
		focuses: ['gesture', 'proportion', 'negative-space'],
		complexity: 'simple',
		coverageTags: ['gesture', 'mundane']
	},
	{
		id: 'people-gesture-reaching-bending',
		label: 'Reaching and bending pose',
		query: 'person reaching bending pose reference photo',
		primarySubject: 'people',
		topic: 'gesture-action',
		focuses: ['gesture', 'construction', 'anatomy'],
		complexity: 'moderate',
		coverageTags: ['gesture', 'body-parts']
	},
	{
		id: 'people-gesture-dance-action',
		label: 'Dance action gesture',
		query: 'dancer action pose gesture reference photo',
		primarySubject: 'people',
		topic: 'gesture-action',
		focuses: ['gesture', 'shape', 'composition'],
		complexity: 'moderate',
		coverageTags: ['gesture']
	},
	{
		id: 'people-gesture-sports-motion',
		label: 'Sports motion pose',
		query: 'athlete motion pose full body reference photo',
		primarySubject: 'people',
		topic: 'gesture-action',
		focuses: ['gesture', 'proportion', 'anatomy'],
		complexity: 'complex',
		coverageTags: ['gesture', 'body-parts']
	},
	{
		id: 'people-full-standing-casual',
		label: 'Casual standing figure',
		query: 'casual standing person full body reference photo',
		primarySubject: 'people',
		topic: 'full-figure',
		sceneTypes: ['everyday-life'],
		focuses: ['proportion', 'construction', 'anatomy'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['mundane', 'body-parts']
	},
	{
		id: 'people-full-seated-chair',
		label: 'Seated figure in chair',
		query: 'person sitting in chair full body reference photo',
		primarySubject: 'people',
		topic: 'full-figure',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['proportion', 'construction', 'negative-space'],
		complexity: 'moderate',
		coverageTags: ['mundane', 'negative-space']
	},
	{
		id: 'people-full-crouching-squatting',
		label: 'Crouching figure',
		query: 'person crouching squatting full body pose reference photo',
		primarySubject: 'people',
		topic: 'full-figure',
		focuses: ['gesture', 'proportion', 'anatomy'],
		complexity: 'moderate',
		coverageTags: ['gesture', 'body-parts']
	},
	{
		id: 'people-full-everyday-task',
		label: 'Figure doing everyday task',
		query: 'person doing everyday task full body reference photo',
		primarySubject: 'people',
		topic: 'full-figure',
		secondarySubjects: ['objects'],
		sceneTypes: ['everyday-life', 'interior'],
		focuses: ['gesture', 'composition', 'proportion'],
		complexity: 'complex',
		coverageTags: ['mundane', 'gesture']
	},
	{
		id: 'people-portrait-front-face',
		label: 'Front portrait',
		query: 'front face portrait reference photo natural light',
		primarySubject: 'people',
		topic: 'portrait-head',
		sceneTypes: ['close-up'],
		focuses: ['proportion', 'anatomy', 'value'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['portrait']
	},
	{
		id: 'people-portrait-profile-head',
		label: 'Profile head',
		query: 'side profile portrait head reference photo',
		primarySubject: 'people',
		topic: 'portrait-head',
		sceneTypes: ['close-up'],
		focuses: ['shape', 'proportion', 'anatomy'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['portrait']
	},
	{
		id: 'people-portrait-three-quarter',
		label: 'Three-quarter portrait',
		query: 'three quarter view portrait head reference photo',
		primarySubject: 'people',
		topic: 'portrait-head',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'proportion', 'light-shadow'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['portrait', 'construction-practice']
	},
	{
		id: 'people-portrait-older-face',
		label: 'Older face portrait',
		query: 'older person portrait face reference photo',
		primarySubject: 'people',
		topic: 'portrait-head',
		sceneTypes: ['close-up'],
		focuses: ['value', 'texture', 'anatomy'],
		complexity: 'complex',
		orientation: 'portrait',
		coverageTags: ['portrait', 'texture-study']
	},
	{
		id: 'people-expression-smile-laugh',
		label: 'Smiling or laughing face',
		query: 'smiling laughing face expression reference photo',
		primarySubject: 'people',
		topic: 'expression',
		sceneTypes: ['close-up'],
		focuses: ['anatomy', 'shape', 'proportion'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['expression', 'portrait']
	},
	{
		id: 'people-expression-surprised',
		label: 'Surprised expression',
		query: 'surprised face expression portrait reference photo',
		primarySubject: 'people',
		topic: 'expression',
		sceneTypes: ['close-up'],
		focuses: ['shape', 'anatomy', 'gesture'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['expression', 'portrait']
	},
	{
		id: 'people-expression-tired-thinking',
		label: 'Tired or thinking expression',
		query: 'tired thinking face expression reference photo',
		primarySubject: 'people',
		topic: 'expression',
		sceneTypes: ['close-up', 'everyday-life'],
		focuses: ['value', 'composition', 'anatomy'],
		complexity: 'moderate',
		orientation: 'portrait',
		coverageTags: ['expression', 'mundane']
	},
	{
		id: 'people-hands-open-palm',
		label: 'Open hand and palm',
		query: 'open hand palm close up reference photo',
		primarySubject: 'people',
		topic: 'hands-feet',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'anatomy', 'shape'],
		complexity: 'moderate',
		coverageTags: ['hands', 'body-parts', 'construction-practice']
	},
	{
		id: 'people-hands-gripping-object',
		label: 'Hand gripping object',
		query: 'hand gripping object close up reference photo',
		primarySubject: 'people',
		topic: 'hands-feet',
		secondarySubjects: ['objects'],
		sceneTypes: ['close-up', 'everyday-life'],
		focuses: ['construction', 'anatomy', 'negative-space'],
		complexity: 'complex',
		coverageTags: ['hands', 'body-parts', 'negative-space']
	},
	{
		id: 'people-hands-holding-cup',
		label: 'Hands holding cup',
		query: 'hands holding mug cup reference photo',
		primarySubject: 'people',
		topic: 'hands-feet',
		secondarySubjects: ['objects'],
		sceneTypes: ['close-up', 'everyday-life'],
		focuses: ['shape', 'construction', 'material'],
		complexity: 'moderate',
		coverageTags: ['hands', 'mundane']
	},
	{
		id: 'people-feet-bare-standing',
		label: 'Bare feet standing',
		query: 'bare feet standing close up reference photo',
		primarySubject: 'people',
		topic: 'hands-feet',
		sceneTypes: ['close-up'],
		focuses: ['anatomy', 'shape', 'proportion'],
		complexity: 'moderate',
		coverageTags: ['feet', 'body-parts']
	},
	{
		id: 'people-feet-tying-shoes',
		label: 'Tying shoes',
		query: 'person tying shoes hands feet reference photo',
		primarySubject: 'people',
		topic: 'hands-feet',
		secondarySubjects: ['objects'],
		sceneTypes: ['everyday-life', 'close-up'],
		focuses: ['gesture', 'construction', 'negative-space'],
		complexity: 'complex',
		coverageTags: ['hands', 'feet', 'mundane']
	},
	{
		id: 'people-clothing-jacket-folds',
		label: 'Jacket folds on figure',
		query: 'person wearing jacket clothing folds reference photo',
		primarySubject: 'people',
		topic: 'clothing-drapery',
		sceneTypes: ['everyday-life'],
		focuses: ['shape', 'material', 'texture'],
		complexity: 'complex',
		orientation: 'portrait',
		coverageTags: ['fabric', 'material-study']
	},
	{
		id: 'people-clothing-long-coat',
		label: 'Long coat drapery',
		query: 'person wearing long coat fabric folds reference photo',
		primarySubject: 'people',
		topic: 'clothing-drapery',
		focuses: ['gesture', 'shape', 'material'],
		complexity: 'complex',
		orientation: 'portrait',
		coverageTags: ['fabric', 'gesture']
	},
	{
		id: 'people-clothing-sleeves-hands',
		label: 'Sleeves and hands',
		query: 'sleeves hands clothing folds close up reference photo',
		primarySubject: 'people',
		topic: 'clothing-drapery',
		secondarySubjects: ['objects'],
		sceneTypes: ['close-up', 'everyday-life'],
		focuses: ['material', 'texture', 'shape'],
		complexity: 'moderate',
		coverageTags: ['fabric', 'hands', 'material-study']
	},
	{
		id: 'people-groups-waiting-line',
		label: 'People waiting in line',
		query: 'people waiting in line everyday reference photo',
		primarySubject: 'people',
		topic: 'groups-crowds',
		secondarySubjects: ['places'],
		sceneTypes: ['public-space', 'everyday-life'],
		focuses: ['gesture', 'composition', 'proportion'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['groups', 'mundane', 'public-space']
	},
	{
		id: 'people-groups-cafe-table',
		label: 'Small group at table',
		query: 'people sitting around cafe table reference photo',
		primarySubject: 'people',
		topic: 'groups-crowds',
		secondarySubjects: ['objects', 'places'],
		sceneTypes: ['public-space', 'interior', 'everyday-life'],
		focuses: ['composition', 'perspective', 'gesture'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['groups', 'interior', 'mundane']
	},
	{
		id: 'people-groups-transit-riders',
		label: 'Transit riders',
		query: 'people riding public transit interior reference photo',
		primarySubject: 'people',
		topic: 'groups-crowds',
		secondarySubjects: ['vehicles-machines', 'places'],
		sceneTypes: ['public-space', 'interior', 'everyday-life'],
		focuses: ['composition', 'perspective', 'negative-space'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['groups', 'transit', 'mundane']
	}
] satisfies readonly ReferenceSearchSeed[];
