import type { ReferenceSearchSeed } from '../reference-seed';

export const placeSeeds = [
	{
		id: 'places-rooms-bedroom-corner',
		label: 'Bedroom corner',
		query: 'ordinary bedroom corner interior reference photo',
		primarySubject: 'places',
		topic: 'rooms',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['interior', 'mundane', 'perspective-practice']
	},
	{
		id: 'places-rooms-living-room',
		label: 'Living room',
		query: 'lived in living room interior reference photo',
		primarySubject: 'places',
		topic: 'rooms',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'composition', 'shape'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['interior', 'mundane', 'clutter']
	},
	{
		id: 'places-rooms-door-window',
		label: 'Door and window wall',
		query: 'room wall door window interior reference photo',
		primarySubject: 'places',
		topic: 'rooms',
		sceneTypes: ['interior'],
		focuses: ['perspective', 'construction', 'light-shadow'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['interior', 'perspective-practice', 'architecture']
	},
	{
		id: 'places-rooms-small-apartment',
		label: 'Small apartment room',
		query: 'small apartment room everyday interior reference photo',
		primarySubject: 'places',
		topic: 'rooms',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['composition', 'perspective', 'negative-space'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['interior', 'mundane', 'negative-space']
	},
	{
		id: 'places-kitchen-counter',
		label: 'Kitchen counter',
		query: 'ordinary kitchen counter everyday objects reference photo',
		primarySubject: 'places',
		topic: 'kitchens-workspaces',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'shape', 'value'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['kitchen', 'interior', 'mundane']
	},
	{
		id: 'places-workspace-cluttered-desk',
		label: 'Cluttered desk workspace',
		query: 'cluttered desk workspace reference photo',
		primarySubject: 'places',
		topic: 'kitchens-workspaces',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'workplace', 'everyday-life'],
		focuses: ['perspective', 'composition', 'shape'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['desk', 'clutter', 'mundane']
	},
	{
		id: 'places-workspace-workbench',
		label: 'Workbench',
		query: 'workbench tools garage workspace reference photo',
		primarySubject: 'places',
		topic: 'kitchens-workspaces',
		secondarySubjects: ['objects'],
		sceneTypes: ['workplace', 'interior'],
		focuses: ['perspective', 'material', 'composition'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['desk', 'clutter', 'material-study']
	},
	{
		id: 'places-kitchen-sink-dishes',
		label: 'Kitchen sink dishes',
		query: 'kitchen sink dishes everyday reference photo',
		primarySubject: 'places',
		topic: 'kitchens-workspaces',
		secondarySubjects: ['objects'],
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['composition', 'value', 'material'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['kitchen', 'mundane', 'clutter']
	},
	{
		id: 'places-public-cafe-interior',
		label: 'Café interior',
		query: 'ordinary cafe interior tables reference photo',
		primarySubject: 'places',
		topic: 'public-interiors',
		secondarySubjects: ['people', 'objects'],
		sceneTypes: ['interior', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['interior', 'public-space', 'mundane']
	},
	{
		id: 'places-public-laundromat',
		label: 'Laundromat',
		query: 'laundromat interior everyday reference photo',
		primarySubject: 'places',
		topic: 'public-interiors',
		secondarySubjects: ['people', 'objects'],
		sceneTypes: ['interior', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'construction', 'composition'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['interior', 'mundane', 'public-space']
	},
	{
		id: 'places-public-waiting-room',
		label: 'Waiting room',
		query: 'waiting room chairs interior reference photo',
		primarySubject: 'places',
		topic: 'public-interiors',
		secondarySubjects: ['people', 'objects'],
		sceneTypes: ['interior', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'negative-space'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['interior', 'public-space', 'negative-space']
	},
	{
		id: 'places-street-sidewalk-row',
		label: 'Sidewalk block',
		query: 'ordinary sidewalk street buildings reference photo',
		primarySubject: 'places',
		topic: 'streets-sidewalks',
		secondarySubjects: ['people', 'vehicles-machines'],
		sceneTypes: ['street', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['street', 'perspective-practice', 'mundane']
	},
	{
		id: 'places-street-alley',
		label: 'Alley perspective',
		query: 'alley street perspective everyday reference photo',
		primarySubject: 'places',
		topic: 'streets-sidewalks',
		sceneTypes: ['street', 'public-space'],
		focuses: ['perspective', 'composition', 'light-shadow'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['street', 'perspective-practice']
	},
	{
		id: 'places-street-intersection',
		label: 'Street intersection',
		query: 'street intersection crosswalk everyday reference photo',
		primarySubject: 'places',
		topic: 'streets-sidewalks',
		secondarySubjects: ['people', 'vehicles-machines'],
		sceneTypes: ['street', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'shape'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['street', 'public-space', 'vehicle']
	},
	{
		id: 'places-storefront-small-shop',
		label: 'Small shop storefront',
		query: 'small shop storefront sidewalk reference photo',
		primarySubject: 'places',
		topic: 'storefronts',
		secondarySubjects: ['objects'],
		sceneTypes: ['street', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'value'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['storefront', 'street', 'architecture']
	},
	{
		id: 'places-storefront-window-display',
		label: 'Window display',
		query: 'store window display reflections reference photo',
		primarySubject: 'places',
		topic: 'storefronts',
		secondarySubjects: ['objects'],
		sceneTypes: ['street', 'public-space'],
		focuses: ['composition', 'material', 'value'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['storefront', 'material-study']
	},
	{
		id: 'places-storefront-market-stall',
		label: 'Market stall',
		query: 'market stall storefront goods reference photo',
		primarySubject: 'places',
		topic: 'storefronts',
		secondarySubjects: ['people', 'objects'],
		sceneTypes: ['public-space', 'street', 'everyday-life'],
		focuses: ['composition', 'shape', 'perspective'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['storefront', 'clutter', 'public-space']
	},
	{
		id: 'places-transit-bus-stop',
		label: 'Bus stop',
		query: 'bus stop people waiting street reference photo',
		primarySubject: 'places',
		topic: 'transit-stops',
		secondarySubjects: ['people', 'vehicles-machines'],
		sceneTypes: ['street', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'gesture'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['transit', 'street', 'mundane']
	},
	{
		id: 'places-transit-train-platform',
		label: 'Train platform',
		query: 'train platform station perspective reference photo',
		primarySubject: 'places',
		topic: 'transit-stops',
		secondarySubjects: ['people', 'vehicles-machines'],
		sceneTypes: ['public-space', 'street'],
		focuses: ['perspective', 'composition', 'construction'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['transit', 'perspective-practice', 'vehicle']
	},
	{
		id: 'places-transit-station-interior',
		label: 'Transit station interior',
		query: 'subway station interior people reference photo',
		primarySubject: 'places',
		topic: 'transit-stops',
		secondarySubjects: ['people', 'vehicles-machines'],
		sceneTypes: ['public-space', 'interior', 'everyday-life'],
		focuses: ['perspective', 'composition', 'light-shadow'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['transit', 'interior', 'public-space']
	},
	{
		id: 'places-parking-lot-cars',
		label: 'Parking lot with cars',
		query: 'parking lot parked cars everyday reference photo',
		primarySubject: 'places',
		topic: 'parking-lots',
		secondarySubjects: ['vehicles-machines'],
		sceneTypes: ['street', 'public-space', 'everyday-life'],
		focuses: ['perspective', 'composition', 'shape'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'perspective-practice', 'mundane']
	},
	{
		id: 'places-parking-garage',
		label: 'Parking garage',
		query: 'parking garage perspective reference photo',
		primarySubject: 'places',
		topic: 'parking-lots',
		secondarySubjects: ['vehicles-machines'],
		sceneTypes: ['public-space'],
		focuses: ['perspective', 'light-shadow', 'composition'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'perspective-practice']
	},
	{
		id: 'places-stairs-apartment',
		label: 'Apartment stairwell',
		query: 'apartment stairwell interior perspective reference photo',
		primarySubject: 'places',
		topic: 'stairs-corridors',
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'construction', 'value'],
		complexity: 'complex',
		orientation: 'portrait',
		coverageTags: ['interior', 'perspective-practice', 'architecture']
	},
	{
		id: 'places-corridor-hallway',
		label: 'Hallway corridor',
		query: 'ordinary hallway corridor perspective reference photo',
		primarySubject: 'places',
		topic: 'stairs-corridors',
		sceneTypes: ['interior', 'everyday-life'],
		focuses: ['perspective', 'composition', 'negative-space'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['interior', 'perspective-practice', 'negative-space']
	},
	{
		id: 'places-architecture-house-front',
		label: 'House front',
		query: 'ordinary house front facade reference photo',
		primarySubject: 'places',
		topic: 'architecture-facades',
		sceneTypes: ['street', 'everyday-life'],
		focuses: ['perspective', 'construction', 'shape'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['architecture', 'perspective-practice', 'mundane']
	},
	{
		id: 'places-architecture-apartment-facade',
		label: 'Apartment façade',
		query: 'apartment building facade windows reference photo',
		primarySubject: 'places',
		topic: 'architecture-facades',
		sceneTypes: ['street'],
		focuses: ['perspective', 'composition', 'construction'],
		complexity: 'dense',
		orientation: 'portrait',
		coverageTags: ['architecture', 'perspective-practice']
	},
	{
		id: 'places-architecture-door-detail',
		label: 'Doorway detail',
		query: 'building doorway architectural detail reference photo',
		primarySubject: 'places',
		topic: 'architecture-facades',
		sceneTypes: ['street', 'close-up'],
		focuses: ['construction', 'material', 'texture'],
		complexity: 'complex',
		orientation: 'portrait',
		coverageTags: ['architecture', 'material-study', 'texture-study']
	}
] satisfies readonly ReferenceSearchSeed[];
