import type { ReferenceSearchSeed } from '../reference-seed';

export const vehicleMachineSeeds = [
	{
		id: 'vehicles-cars-parked-street',
		label: 'Parked car on street',
		query: 'parked car on street perspective reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'cars-trucks',
		secondarySubjects: ['places'],
		sceneTypes: ['street', 'everyday-life'],
		focuses: ['perspective', 'construction', 'shape'],
		complexity: 'moderate',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'street', 'perspective-practice']
	},
	{
		id: 'vehicles-cars-interior-dashboard',
		label: 'Car interior dashboard',
		query: 'car interior dashboard reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'cars-trucks',
		sceneTypes: ['interior', 'close-up'],
		focuses: ['perspective', 'construction', 'material'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'interior', 'mechanical-detail']
	},
	{
		id: 'vehicles-trucks-delivery',
		label: 'Delivery truck',
		query: 'delivery truck parked street reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'cars-trucks',
		secondarySubjects: ['places'],
		sceneTypes: ['street', 'everyday-life'],
		focuses: ['construction', 'perspective', 'value'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'street', 'mundane']
	},
	{
		id: 'vehicles-bikes-bicycle-side',
		label: 'Bicycle side view',
		query: 'bicycle side view reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'bikes-motorcycles',
		sceneTypes: ['isolated-subject', 'street'],
		focuses: ['construction', 'shape', 'negative-space'],
		complexity: 'complex',
		coverageTags: ['vehicle', 'negative-space', 'construction-practice']
	},
	{
		id: 'vehicles-bikes-scooter-parked',
		label: 'Parked scooter',
		query: 'parked scooter street reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'bikes-motorcycles',
		secondarySubjects: ['places'],
		sceneTypes: ['street', 'everyday-life'],
		focuses: ['construction', 'perspective', 'material'],
		complexity: 'complex',
		coverageTags: ['vehicle', 'street', 'material-study']
	},
	{
		id: 'vehicles-bikes-motorcycle-detail',
		label: 'Motorcycle detail',
		query: 'motorcycle engine wheel detail reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'bikes-motorcycles',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'material', 'texture'],
		complexity: 'dense',
		coverageTags: ['vehicle', 'mechanical-detail', 'material-study']
	},
	{
		id: 'vehicles-buses-city-bus',
		label: 'City bus',
		query: 'city bus street perspective reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'buses-trains',
		secondarySubjects: ['places', 'people'],
		sceneTypes: ['street', 'public-space'],
		focuses: ['perspective', 'construction', 'composition'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'transit', 'street']
	},
	{
		id: 'vehicles-trains-platform',
		label: 'Train at platform',
		query: 'train at platform perspective reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'buses-trains',
		secondarySubjects: ['places', 'people'],
		sceneTypes: ['public-space', 'street'],
		focuses: ['perspective', 'construction', 'value'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'transit', 'perspective-practice']
	},
	{
		id: 'vehicles-boats-dock',
		label: 'Boats at dock',
		query: 'boats at dock reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'boats-aircraft',
		secondarySubjects: ['nature', 'places'],
		sceneTypes: ['landscape', 'public-space'],
		focuses: ['perspective', 'composition', 'shape'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'water', 'landscape']
	},
	{
		id: 'vehicles-aircraft-small-plane',
		label: 'Small aircraft',
		query: 'small airplane parked reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'boats-aircraft',
		sceneTypes: ['isolated-subject', 'public-space'],
		focuses: ['construction', 'perspective', 'shape'],
		complexity: 'complex',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'construction-practice']
	},
	{
		id: 'vehicles-construction-excavator',
		label: 'Excavator',
		query: 'excavator construction machinery reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'construction-machinery',
		secondarySubjects: ['places'],
		sceneTypes: ['workplace'],
		focuses: ['construction', 'perspective', 'material'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'mechanical-detail', 'construction-practice']
	},
	{
		id: 'vehicles-construction-tractor-crane',
		label: 'Tractor or crane',
		query: 'tractor crane construction machine reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'construction-machinery',
		sceneTypes: ['workplace', 'public-space'],
		focuses: ['construction', 'shape', 'perspective'],
		complexity: 'dense',
		orientation: 'landscape',
		coverageTags: ['vehicle', 'mechanical-detail']
	},
	{
		id: 'vehicles-mechanical-engine',
		label: 'Engine parts',
		query: 'engine parts mechanical detail reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'mechanical-details',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'material', 'texture'],
		complexity: 'dense',
		coverageTags: ['mechanical-detail', 'material-study', 'texture-study']
	},
	{
		id: 'vehicles-mechanical-gears-pipes',
		label: 'Gears and pipes',
		query: 'gears pipes machinery detail reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'mechanical-details',
		sceneTypes: ['close-up'],
		focuses: ['construction', 'shape', 'negative-space'],
		complexity: 'dense',
		coverageTags: ['mechanical-detail', 'negative-space', 'construction-practice']
	},
	{
		id: 'vehicles-mechanical-control-panel',
		label: 'Control panel',
		query: 'machine control panel buttons reference photo',
		primarySubject: 'vehicles-machines',
		topic: 'mechanical-details',
		sceneTypes: ['close-up', 'workplace'],
		focuses: ['composition', 'shape', 'material'],
		complexity: 'dense',
		coverageTags: ['mechanical-detail', 'material-study']
	}
] satisfies readonly ReferenceSearchSeed[];
